"""Build the distributable monsoonplus.zip.

    python scripts/package.py

Produces ``dist/monsoonplus.zip`` containing everything a reader needs to rebuild,
run and deploy the project, and nothing they should not receive.

Deliberately excluded
---------------------
* ``.env`` and any credential file -- the whole point of .gitignore.
* ``.venv/``, ``node_modules/`` -- hundreds of megabytes, recreated by one command.
* ``ml/data/raw/`` -- the 57 MB METR-LA download; re-fetched by the loader.
* ``ml/checkpoints/*.pt`` -- binary, regenerated by training. (Pass ``--with-checkpoint``
  to include it if you want the backend to work without retraining.)
* ``frontend/dist/`` -- build output, recreated by ``npm run build``.
* ``__pycache__``, ``.pytest_cache``, editor and OS cruft.

Included even though gitignored
-------------------------------
* ``frontend/public/data/*.json`` -- the committed prediction files ARE the deployed
  site's data layer. Without them a fresh unzip shows an error state.
"""

from __future__ import annotations

import argparse
import fnmatch
import os
import sys
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = REPO_ROOT / "dist"

# Directories pruned entirely during the walk (cheap, and avoids walking node_modules).
PRUNE_DIRS = {
    ".git",
    ".venv",
    "venv",
    "env",
    "node_modules",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".vscode",
    ".idea",
    "dist",
    ".vite",
    "snapshots",
    "raw",
}

EXCLUDE_PATTERNS = [
    ".env",
    ".env.*",
    "*.pyc",
    "*.pyo",
    "*.log",
    "*.h5",
    "*.npy",
    "*.db",
    "*.key",
    "*secret*",
    "credentials.json",
    ".DS_Store",
    "Thumbs.db",
    "desktop.ini",
    "*.local",
]

# Files that are gitignored but MUST ship.
FORCE_INCLUDE = [
    "frontend/public/data/predictions_synthetic_chennai.json",
    "frontend/public/data/predictions_metr_la.json",
    "frontend/public/data/predictions_live_template.json",
    "frontend/public/data/model_card.json",
    ".env.example",
]


def is_excluded(relative: Path) -> bool:
    name = relative.name
    if name == ".env.example":
        return False
    for pattern in EXCLUDE_PATTERNS:
        if fnmatch.fnmatch(name, pattern):
            return True
    return False


def collect_files(with_checkpoint: bool) -> list[Path]:
    selected: list[Path] = []

    for root, dirs, files in os.walk(REPO_ROOT):
        root_path = Path(root)
        dirs[:] = [d for d in dirs if d not in PRUNE_DIRS]

        for filename in files:
            path = root_path / filename
            relative = path.relative_to(REPO_ROOT)

            if is_excluded(relative):
                continue
            if relative.suffix in (".pt", ".pth") and not with_checkpoint:
                continue
            selected.append(path)

    for forced in FORCE_INCLUDE:
        path = REPO_ROOT / forced
        if path.exists() and path not in selected:
            selected.append(path)

    return sorted(set(selected))


def audit(files: list[Path]) -> list[str]:
    """Last line of defence: refuse to ship anything that looks like a credential."""
    problems: list[str] = []
    for path in files:
        relative = path.relative_to(REPO_ROOT).as_posix()
        if relative == ".env" or relative.startswith(".env.") and relative != ".env.example":
            problems.append(f"credential file would be shipped: {relative}")
        if relative.endswith((".key", ".pem")):
            problems.append(f"key file would be shipped: {relative}")

    # Scan small text files for anything resembling a live TomTom key assignment.
    # Documentation legitimately shows a worked example, so obvious placeholders are
    # recognised rather than blocking the build -- but the scan still runs over .md,
    # because a real key pasted into a README is exactly the mistake worth catching.
    placeholder_markers = (
        "your", "example", "placeholder", "here", "xxx", "abcdef",
        "<", "paste", "redacted", "changeme",
    )
    for path in files:
        if path.suffix not in (".py", ".js", ".jsx", ".json", ".md", ".yml", ".yaml"):
            continue
        # This file contains the detection strings themselves.
        if path.resolve() == Path(__file__).resolve():
            continue
        try:
            if path.stat().st_size > 2_000_000:
                continue
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        for line in text.splitlines():
            stripped = line.strip()
            if "TOMTOM_API_KEY" in stripped and "=" in stripped:
                _, _, value = stripped.partition("=")
                value = value.strip().strip("'\"").strip()
                # Allow the documented empty placeholder and code that reads the env var.
                if not value or value.startswith(("${", "os.", "process.", "secrets.")):
                    continue
                # Markdown tables and prose mention the variable name constantly. A real
                # key is a single bare token, so anything with a pipe or whitespace in it
                # is documentation, not a credential.
                if "|" in value or any(ch.isspace() for ch in value):
                    continue
                lowered = value.lower()
                if any(marker in lowered for marker in placeholder_markers):
                    continue
                if len(value) > 8 and lowered not in ("none", "null", "true", "false"):
                    problems.append(
                        f"possible live key in "
                        f"{path.relative_to(REPO_ROOT).as_posix()}: {value[:6]}..."
                    )
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description="Package monsoonplus for distribution")
    parser.add_argument(
        "--with-checkpoint",
        action="store_true",
        help="include ml/checkpoints/*.pt (larger, but the backend then works immediately)",
    )
    parser.add_argument("--name", default="monsoonplus.zip")
    args = parser.parse_args()

    files = collect_files(args.with_checkpoint)

    problems = audit(files)
    if problems:
        print("REFUSING TO PACKAGE -- credential audit failed:")
        for problem in problems:
            print(f"  - {problem}")
        return 1

    required = [
        "README.md",
        "LICENSE",
        "config/segments.json",
        "frontend/package.json",
        "frontend/public/data/predictions_synthetic_chennai.json",
        "notebooks/monsoonplus_colab_training.ipynb",
    ]
    relative_set = {p.relative_to(REPO_ROOT).as_posix() for p in files}
    missing = [item for item in required if item not in relative_set]
    if missing:
        print("REFUSING TO PACKAGE -- required files missing:")
        for item in missing:
            print(f"  - {item}")
        return 1

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    archive_path = OUTPUT_DIR / args.name

    with zipfile.ZipFile(archive_path, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in files:
            relative = path.relative_to(REPO_ROOT)
            archive.write(path, arcname=str(Path("monsoonplus") / relative))

    size_mb = archive_path.stat().st_size / 1e6
    print(f"packaged {len(files)} files -> {archive_path}  ({size_mb:.1f} MB)")

    by_top: dict[str, int] = {}
    for path in files:
        top = path.relative_to(REPO_ROOT).parts[0]
        by_top[top] = by_top.get(top, 0) + 1
    print("\ncontents by top-level entry:")
    for top, count in sorted(by_top.items(), key=lambda kv: -kv[1]):
        print(f"  {top:<28} {count:>4} file(s)")

    print("\nexcluded on purpose: .env, .venv/, node_modules/, ml/data/raw/, dist/")
    if not args.with_checkpoint:
        print("excluded: ml/checkpoints/*.pt  (use --with-checkpoint to include)")
    print("credential audit: PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
